### ISSUE TITLE
Solve time shift between bidding and dispatch

### ISSUE THREAD

**Issue by adamsjohanna** [assume-framework/assume#111]
The times when the bids are calculated and the dispatch is executed do not match. The implemented order is for example:
- calculate_bids() (including operational_window) for 4:00 - 5:00 am
- execute_dispatch() for 3:00 - 4:00 (also adjusting the SOC)
- calculate_bids() for 5:00 - 6:00 (using the SOC from 3:00 am)
- ...

This should be addressed when changing to 24h bidding.

**Comment by maurerle** [comment]
When you set `first_delivery: 0h` you receive the following events in order:

* calculate_bids for 4:00 - 5:00 - at 4:00
* execute_dispatch for 4:00 - 5:00 - at 5:00
* calculate_bids for 5:00 - 6:00 - at 5:00

So this is an artifact of having a delay between currently bidding and the time for which the bid happens
