### ISSUE TITLE
Remarks from Remark

### ISSUE THREAD

**Issue by maurerle** [assume-framework/assume#133]
I just discussed a few code related things with Eike which are:

- [x]  missing documentation for market and market mechanisms
  -  unclear when which manipulations are necessary, which items have to be sent back
  -  unclear which parameters are needed
  - how one can implement own market mechanism
- [x]  market clearing seems to do more than just clearing the market
  -  one option for the future would be to create MarketClearing as an object instead of a callback, which has the following functions:
```python
class MarketClearing:
  grid: Any # <- we can store things here for additional data like grid
  def clear_market(orderbook, products) -> accepted: Orderbook, rejected: Orderbook, on_hold: Orderbook
    ...

  def calculate_meta(accepted: Orderbook) -> meta_dict:
    ...
```

- [x]  currently traders which did not get any offer, are not getting informed about it
- [x]  currently traders are not informed about if an offer is rejected (which could free up reserved space in a bidding agent)
- [ ]  clearing related things
  - [ ]  clearing can have 4 different cases of intersection, which might not be handled in the way they should be from an economic perspective
  - [x]  it can happen, that some orders are sent back splitted due to the way our market mechanism currently works for `pay_as_clear` and `pay_as_bid`

**Comment by nick-harder** [comment]
@maurerle I believe now all the issues are adressed or?

**Comment by nick-harder** [comment]
can we close this issue @maurerle ?

**Comment by nick-harder** [comment]
as there was no new activity in this issue and the problems have been resolved, this issue is now closed
