### ISSUE TITLE
Release first Version

### ISSUE THREAD

**Issue by maurerle** [assume-framework/assume#136]
I would like to release a 0.1.0 version of this framework in the near future:

To do this, the following steps are required:

- [ ] Create a CITATION.cff
  - https://citation-file-format.github.io/
  - https://github.com/pommes-public/pommesdispatch/blob/dev/CITATION.cff
- [ ] set version to 0.1.0 in pyproject.toml
- [ ] change name in pyproject.toml to `assume-framework` instead of `assume_framework`?
- [ ] create a release on github - that will create a release on Zenodo as well and will be published here: https://doi.org/10.5281/zenodo.8088760 - so we can use this general DOI in the citation.cff as well
- [ ] publish package to pypi under the name `assume-framework` (run `poetry publish` with username and password)

**Comment by nick-harder** [comment]
I find asusme-frameowork as a package name pretty good. I would be also interested in learning how the last 2 steps are done. @maurerle please let me know when you have time so we can do it together

**Comment by nick-harder** [comment]
released!!!
