### ISSUE TITLE
Improve Dashboard

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#142]
To prepare for the workshop, we should improve the KPIS and data shown in the dashboard. In general, that includes the following points:

**Normal Dash Board** (KA)
- [x] depict unit-wise bids in particular the ratio between bid volume and accepted volume
- [x] show profit and cash flow of units and SoC 
- [x] Improve the description in the dashboard itself
- [x] only show evaluation run and not learning episodes (kim)
- [x] schreibe rejected orders auch in order book (Florian)
- [x] 1 plot accepted price and offered price and one for volume similary (kim)

**Learning Dashboard** (KA)

- [x] setup general dashboard structure
- [x] show average episode reward
- [x] make plotting results over all episodes in time series plot possible
- [x] split simulation_id and episode number in dB
- [x] fix overwrite in db, so that old episode runs with the same simulation_id are deleted
- [x] plot reward as time graph per episode over each other
- [x] visualize the exploration
- [x] actions of units
- [x] bids acceptance und rejection (kim)
- [x] show validation run (kim)

**Comment by nick-harder** [comment]
@maurerle isn't this already done? should we close this issue?
