### ISSUE TITLE
Testing with Torch

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#143]
Implement a way of configuring the unit test so that they are done only if we use learning. Since torch needs to be included in the tests and we would like to have it as a weak requirement only necessary for learning.

This will only be done after the learning is settled in.

**Comment by maurerle** [comment]
One can add tests, which are only run if a marker is set: https://docs.pytest.org/en/6.2.x/mark.html#registering-marks

If we add in `pyproject.toml`:
```toml
[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "require_learning",
]
```

learning tests:
```python
@pytest.mark.require_learning
def test_learning():
    pass
```

can be skipped if we run pytest as `pytest -m "not require_learning"`.

**Comment by nick-harder** [comment]
This issue has been resolved
