### ISSUE TITLE
Dokumentation improvements needed

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#146]
Installation process tested with two assume newbies:

**Read Me**
- [ ] Documentation from read_the_docs and github read_me  is different
- [x] for the run example docker is actually needed, should have a preconfigured run without docker ready
- [x] add modification to install command for development section
- [x] #148
- [x] merge Quickstart with docker and the usage of dashboard etc.
- [x] include some basic commands for docker, so that people do not have to search for them, like stopping containers etc
- [x] include trouble shooting for error of connection with postgresql

**Read The Docs**
- [ ]  Read the Docs in "Example CRM Market" why is the delivery and bidding scheduled during the same time in the EOM 
- [ ] more description of "count" variable needed - seems to lead to some confusion 

**Units:**

- [x] power plants
- [x] storage units
- [x] demand

**Common:**

- [x] Outputs role
- [ ] Config files
  > I would expect to have a config.yml.example somewhere which has comments to clarify everything.
Additionally, a documentation of the scenarios on readthedocs.
- [x] reinforcment learning 

**Strategies**
- [x] reinforcement learning startegies
- [x] conventional strategies

**Markets:**

- [x] Market config

**General**
- [x] scenarios
- [ ] establish general scenario description layout?

**Comment by nick-harder** [comment]
further documentation improvements will be adressed in a seperate issue
