### ISSUE TITLE
Replace current_status, current_down_time, etc. by function get_operation_time in base_unit

### ISSUE THREAD

**Issue by adamsjohanna** [assume-framework/assume#156]
Counting the downtime and market success depends on the different clearings. Calculating this from unit.outputs should reduce the complexity. Defining it for all in base.py will also reduce errors when adding new clearings or units.

**Comment by maurerle** [comment]
There is already `get_operation_time` and `get_soc_before` in base which should be usable for these things.
I made first steps on the branch `remove_current_status` but did not finish yet

**Comment by maurerle** [comment]
fixed by #164 160
