### ISSUE TITLE
Writing to db of comlex orders after running a simple simulation before that doesn't work

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#188]
I get an error sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "min_acceptance_ratio" of relation "market_orders" does not exist

This only happens if you run a simple simulation beforehand. I believe this happens because this column doesn't exist in the db.

**Comment by maurerle** [comment]
The fix for this is to catch the error, read everything from the existing table (pd.read_sql), join the two dfs and write it again with if_exists="replace"

**Comment by nick-harder** [comment]
I mean this is a pretty bad solution if you already have like 100+ simulations in the db and now you need to get it all and write again. Isn't there a better solution? Can we already initially create the tables with those values we know we have (like min-acceptance)? so the problem doesn't even occur?
