### ISSUE TITLE
Refurbish the workshop material

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#220]
After the workshop we would like to make the coding examples accessible for all potential Assume users. The idea is to refurbish them for tutorials on the read-the-docs page as well as bake it into jupyter notebooks. 

- [ ] migrate examples from workshop branch to tutorial folder on main

- [ ] learning examples in read-the-docs tutorial @kim-mskw 
- [x] learning examples in jupyter notebook @kim-mskw 

- [x] unit examples in read-the-docs tutorial @Manish-Khanra 
- [ ] unit examples in jupyter notebook @kim-mskw 

Establish communication channel to participants

- [x] create an e-mail group @nick-harder 
- [ ] communicate tutorials and news to participants @nick-harder

**Comment by nick-harder** [comment]
task is seperated into different issues
