### ISSUE TITLE
Central unit operator for learning units needed

### ISSUE THREAD

**Issue by adamsjohanna** [assume-framework/assume#228]
The buffer does only work, if only one unit operator for all learning units is defined. 
If there are more unit operators defined, the values in the buffer are ether overwritten or there are even errors due to dimension issues.
This could be solved through an assignment of the learning units to one new operator, which is missing right now.

**Comment by maurerle** [comment]
Why do you require multiple unit operators though?
Which example are you using?

**Comment by adamsjohanna** [comment]
Well, right now I don't need it. But if I do for some reason specify different operators, the whole simulation crashes or uses wrong values without saying anything. So to keep the usage rules easy to follow, I would suggest ether some Error message or an automatic collection of all learning units.

**Comment by nick-harder** [comment]
During the initial discussions we decided to use the same unit operator when in learning mode disregarding what the user specifies. I somehow thought this was already in place. I believe, it would be important to add this internal check and during learning mode assign all units to a single operator.

**Comment by kim-mskw** [comment]
I am pretty sure I had this in place at some point and we got rid of it. I will reimplement this check.

**Comment by nick-harder** [comment]
@kim-mskw @adamsjohanna is this issue still open?
