### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#232]
We should add a detailed documentation about:

- [x] introduction
- [x] installation
  - [x] pip
  - [x] docker
  - [x] docs
- [ ] Contributing @maurerle 
- [x] add screenshots of the dashboards to be able to see this without install @kim-mskw 
  - [x] Grafana Basic dashboard
  - [x] Comparison Dashboard
  - [x] Reinforcement Learning Dashboard
- [ ] Config File description (input/output is missing) one big table @nick-harder 
  - [ ] add table for config files for powerplants
  - [ ] add time series format
  - [ ] describe config tables
- [x] example files as jupyter notebook #233 
  1. Basic thing from dach
  2. more comprehensive (what if i have more units and want to add them in an automated way?)
  3. load config from a file
  4. run actual simulation and look at dashboard
- [ ] description of how simulations from AMIRIS can be used @maurerle
- [ ] market config files
  - [x] market config params
  - [ ] Contract Market (WIP) @maurerle 
  - [ ] description of currently implemented market clearing mechanism @adamsjohanna 
    - [ ] pay as clear
    - [ ] pay as bid
    - [ ] pay as clear with complex clearing
  - [ ] adding new market mechanisms
- [ ] bidding strategies
  - [ ] naive strategy
  - [ ] flexable strategy @nick-harder 
  - [ ] flexable storage strategy @adamsjohanna 
  - [ ] dmas strategies @maurerle 
  - [x] adding new strategies @Manish-Khanra 
- [x] Reinforcement Learning
  - [x] Actor
  - [x] Critic
  - [x] Buffer @kim-mskw 
- [x] Units Operator  
  - [x] power plant
  - [x] storage unit
  - [x] demand unit
- [x] list of available scenarios (see #249)
- [ ] output descriptions (shown in example 2)
  - [ ] which values are available as output of units? profit, output
  - [ ] which values are available as market outputs? demand, supply, price...

**Comment by kim-mskw** [comment]
- [ ] Add detailed table about the simulations keep overview table with small description

**Comment by kim-mskw** [comment]
Decided to add the API References to the general descriptions of the framework parts. 

First describe it in text similar to it is done with the learning doc and then at the bottom we reference the respective API References.
