### ISSUE TITLE
Implement Storage Units

### ISSUE THREAD

**Issue by adamsjohanna** [assume-framework/assume#27]
Implement storage.py in units-folder according to implementation in flexABLE

**Comment by maurerle** [comment]
The remarks from here are still relevant:
https://github.com/assume-framework/assume/pull/67

I just merged the current state so that the branches are not diverging too much.
It would also be very good to have some tests, otherwise we will spend a lot more time debugging issues..

**Comment by nick-harder** [comment]
Units are now developed. EOM bidding strategies from flexABLE are also included. Next step is to include also the CRM bidding strategies.

**Comment by nick-harder** [comment]
It was decided to change CRM bidding strategies from flexABLE to different ones since those do not work well with our architecture. This requires some time, and extra carefull testing since flexABLE cannot be used for validation.

**Comment by maurerle** [comment]
Can you elaborate on what is different?

**Comment by adamsjohanna** [comment]
With @maurerle we just discussed, that depending on the order of clearing the markets, the submitted bids to the preceding market have to be taken into account. In flexABLE this was done by calculating a theoretical SOC for the CRM market by running the calculateBidEOM() function. 
In our version we can simply subtract/add the bids from the operational windows. This is a simpler, but not validated method, so additional testing is required.

**Comment by maurerle** [comment]
We also discussed how storages would/should behave
* that checks in `calculate_operational_window` should go into `execute_current_dispatch`
* how the storage would behave
* it is the easiest to provide the storage strategy with the (already given) eom price forecast
* in the future for validation with flexable we can create a unit specific price forecast just like flexable does in `calculateBidEOM`, this should be exchangable somehow (through the bidding strategy)

**Comment by adamsjohanna** [comment]
For now I implemented the first point (that checks in `calculate_operational_window` should go into `execute_current_dispatch`),  but I am confused in the given start and end times: in units_operator.py, in the function`handle_market_feedback` there are the two functions `self.set_unit_dispatch()` with `start` and `end` and `self.write_actual_dispatch()` with `now` and `start`. Those time slots do not match.
The dispatch is now executed on an earlier hour than the dispatch is set. Can this be correct?
