### ISSUE TITLE
Add LSTM policy

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#270]
To enhance the RL method currently implemented in ASSUME, we want to add diffrent policies and buffers. 

This includes an LSTM policy for the actor and/or critic instead of the plain NN to have some time awareness. 

Furthermore, a new buffer is implemented, which uses not random sampling but importance sampling instead.

**Comment by nick-harder** [comment]
As mentioned by @kim-mskw during the development meeting, the work on the LSTM policy provided good results and can be merged with the framework soon
