### ISSUE TITLE
let bid_type and node_id be created automatically so that they are in the DB

### ISSUE THREAD

**Issue by maurerle** [assume-framework/assume#314]
otherwise we need to have a run with a respective simulation before the dashboards work

**Comment by nick-harder** [comment]
@maurerle hi, would you have some time to adress this issue, so we could also fix the dashboards?

**Comment by maurerle** [comment]
I can not reproduce this anymore - can you?
I think this is fixed as we renamed node_id to node as it already existed.

We could rename it every where to node_id - to be consistent with market_id - but that would be a different issue, right?
