### ISSUE TITLE
Warning: ignored suffixes in the complex clearing algorithm

### ISSUE THREAD

**Issue by adamsjohanna** [assume-framework/assume#326]
"Not prio 1"

When using pyomo 6.7 or newer, the warning `WARNING:pyomo.repn.plugins.lp_writer:EXPORT Suffix 'dual' found on 1 
block:    dual LP writer cannot export suffixes to LP files.  Skipping` is generated when using the complex clearing with the flexableEOM strategy.
See also:
https://github.com/Pyomo/pyomo/pull/2982

Probably it is connected to the dual variables in the optimization problem.

**Comment by maurerle** [comment]
This is not fixed when using pyomo 6.7 or newer.
We just removed the warning from the tutorial 6 by installing pyomo < 6.7 - so we still need a way to remove the warning message ^^

**Comment by nick-harder** [comment]
@maurerle somehow i never get this warning when running locally, only on collab. Do you get it when running locally?

**Comment by maurerle** [comment]
You only get the warning if you have pyomo 6.7 installed and are running an example with the advanced pyomo clearing.
I bet you just have a not so recent pyomo..?

I did not reproduce it though. But I am pretty sure it is that way
