### ISSUE TITLE
Adjust observations for learning agents for best learning performance and speed

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#339]
In the initial implementation of RL we disregarede the historic values in the observation space metioned in Harder et al. These need to be added back to ensure good performance  for larger simulations.

**Comment by nick-harder** [comment]
As mentioned by @kim-mskw during a development meeting, reducing the observation space has also improved the performance. We should investigate this as part of the work

**Comment by nick-harder** [comment]
This is done already. Next step would be to be able to add historical values to the forecaster
