### ISSUE TITLE
Switch to PyOptInterface instead of pyomo for speed benefits

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#342]
[PyOptInterface](https://metab0t.github.io/PyOptInterface/index.html) is a new and very fast interpreter for optimization. Its [speed](https://metab0t.github.io/PyOptInterface/benchmark.html) is like 10x faster compared to pyomo, so it would be beneficial for us to switch all clearing algorithms and other parts using pyomo to this new framework, so even solving large scenarios would be fast.

**Comment by metab0t** [comment]
Thanks for your attention!

PyOptInterface will be a good choice when the time to construct optimization model becomes the bottleneck. If you have any issues or feature requests when you switch, welcome to ping me.

**Comment by nick-harder** [comment]
@metab0t thanks for the reply! After some consideration we came to the conslusion, that we would like to get back to this topic in some time when the framework is more mature.
