### ISSUE TITLE
Redispatch Germany: Error while running the code

### ISSUE THREAD

**Issue by paragpatil39** [assume-framework/assume#386]
I was working on the multi-node model of Germany for redispatch with node-wise distributed demands, and renewable & non-renewable generators. I couldn't figure out and resolve the following error.  

![image](https://github.com/assume-framework/assume/assets/58882654/bf31121e-59fc-4954-b7d1-7e23d8c15100)

**Comment by nick-harder** [comment]
@paragpatil39 hi Parag, I would need a bit more details to help you. Please provide me on what branch you are working and how to reprodue the error (which example are you running?)

**Comment by paragpatil39** [comment]
@nick-harder Hi Nick, I am working on branch redispatch_Germany on example 04a.

**Comment by nick-harder** [comment]
@paragpatil39 the problem is in your demand_df.csv file. the index starts with a format YY-DD-MM, and on the 13th of January it switches to YY-MM-DD, which is the correct format. Please fix the input file and it should be fine

**Comment by nick-harder** [comment]
@paragpatil39 was the problem solved?
