### ISSUE TITLE
+/- convention for power plants orders and charging 

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#409]
During a discussion with a student, it turns out that 
1. the convention of buy and sell orders is not properly documented 
2. I am pretty sure there is a bug in the Grafana dashboard SQL queries for the bid prices and bid volume of the storages (again +/- convention) 
3. 
**Queries bid price:**

SELECT
  $__timeGroupAlias(start_time,$__interval),
  CASE WHEN avg(accepted_volume) < 0 THEN avg(accepted_price::float) END AS "Accepted price Discharge",
  CASE WHEN avg(accepted_volume) >= 0 THEN avg(accepted_price::float) END AS "Accepted price Charge",
  **CASE WHEN avg(volume) < 0 THEN avg(price) END AS "Bid price Discharge",
  CASE WHEN avg(volume) >= 0 THEN avg(price) END AS "Bid price Charge",**
  concat(unit_id, ' - ', market_id) as "unit_id"
FROM market_orders
WHERE
  $__timeFilter(start_time) AND
  unit_id in ($Storage_Units) AND
  simulation = '$simulation'
GROUP BY 1, unit_id, market_id
ORDER BY 1

**Queries bid volume:**

SELECT
  $__timeGroupAlias(start_time,$__interval),
  avg(accepted_volume) AS "Accepted volume:",
  **CASE WHEN avg(volume) < 0 THEN avg(volume) END AS "Bid volume charge:",
  CASE WHEN avg(volume) >= 0 THEN avg(volume) END AS "Bid volume discharge:",**
  concat(unit_id, ' - ', market_id) as "unit_id"
FROM market_orders
WHERE
  $__timeFilter(start_time) AND
  unit_id in ($Storage_Units) AND
  simulation = '$simulation'
GROUP BY 1, unit_id, market_id
ORDER BY 1

While I thought about it, I confused myself several times; hence, input from someone who implemented the storages would be greatly appreciated.

**Comment by maurerle** [comment]
The volume is always the amount of energy which is put on (if positive) the market or (if negative) taken from the market.
A demand does always have a negative volume - as it buys/consumes energy .
A powerplant does always have a positive volume - as it produces energy.

As a storage, I am producing Energy on the market when I discharge.
So `CASE WHEN avg(volume) >= 0 THEN avg(volume) END AS "Bid volume discharge:",` is correct.

The `Queries bid price:` query you posted should be corrected.

**Comment by kim-mskw** [comment]
Okay, thanks for the explanation! The 2 queries contradict each other. From your explanation, I understand that:
CASE WHEN avg(volume) < 0 THEN avg(price) END AS "Bid price Discharge",

Is not correct, right?

**Comment by maurerle** [comment]
Exactly :)

**Comment by kim-mskw** [comment]
Okay, thanks! I was confused because you wrote Queries Bid Price is Correct. All corrected :)
