### ISSUE TITLE
Notebooks are not working

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#460]
Currently, on the main branch the notebooks are not working. I am assuming it is because the installations were renamed. In particular, 08 is not functioning, which also leads 09 to fail.

**Comment by nick-harder** [comment]
@kim-mskw are they failing locally or on the collab?

**Comment by kim-mskw** [comment]
In collab

**Comment by nick-harder** [comment]
@kim-mskw yup, I know that, we changed pyomo to be included and the notebooks were updated, and we wanted to make a new release, but a big change from @maurerle  was created, so I wanted to merge that as well and create a new release afterwards. the notebooks will become functional afterwards. or should we temporarily fix them now and remove the fixes later?

**Comment by maurerle** [comment]
I would rather wait for it, as there currently is no workshop upcoming or is this crucial? @kim-mskw

**Comment by kim-mskw** [comment]
Sorry, then I am not up to date. I have a lecture in which I would like to use one of them, but it is only in two weeks.

**Comment by nick-harder** [comment]
This will be fixed with the next release next week
