### ISSUE TITLE
Wrong fuel price handling for pypsa power plants

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#461]
The marginal costs from pypsa are stored in the forecaster as the fuel prices. 

`        world.add_unit(
            generator.name,
            unit_type,
            "powerplant_operator",
            {
                "min_power": generator.p_nom_min,
                "max_power": max_power,
                "bidding_strategies": bidding_strategies[generator.name],
                "technology": "conventional",
                "node": generator.node,
                "efficiency": generator.efficiency,
                "fuel_type": generator.carrier,
                "ramp_up": ramp_up,
                "ramp_down": ramp_down,
                "min_operating_time": generator.min_up_time,
                "min_down_time": generator.min_down_time,
            },
            NaiveForecast(
                index,
                fuel_price=generator.marginal_cost,
                availability=av,
            ),
        )`

However, later, in calc_simple_marginal_cost, they are again interpreted as fuel prices, which potentially leads to them being divided twice by their efficiency. Are we sure that pypsa stores fuel prices as the marginal costs? From the definition that I know, they should already account for the efficiency. 

` def calc_simple_marginal_cost(self,): fuel_price = self.forecaster.get_price(self.fuel_type)`

**Comment by nick-harder** [comment]
@kim-mskw where is this snippet coming from?

**Comment by nick-harder** [comment]
@kim-mskw as far as I know, pypsa doesn't calculate the marginal costs itself, you need to provide them as a constant value or as a time series. So here we should not treat them as fuel prices, your assumtion is correct. Or what was the idea when you wrote this part of the pypsa loader @maurerle?

**Comment by maurerle** [comment]
In `load_pypsa` of the loader_pypsa unit, we have the above snippet, in which we add the values from pypsa to our forecast as prices: `fuel_price=generator.marginal_cost`

I think the quesion here is whether pypsa did already divide this by the efficiency, and if so, we would have to multiply it by the efficiency or do something else, so that the efficiency is only respected once.

I don't quite know which behavior is correct here.

**Comment by nick-harder** [comment]
@maurerle in pypsa the marginal costs already are the final marginal costs. we cannot use them as fuel prices. Pypsa also considers the efficiency only for the primary energy consumption constraints and nothing more.

**Comment by nick-harder** [comment]
fixed in #509
