### ISSUE TITLE
Integrate forecast role 

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#47]
Want to have a individual forecast role that can send forecasts to each agent, which allows diverging forecasts in the future.

**Comment by maurerle** [comment]
I think that a neat way to implement this would be that a forecast role is part of each units_operator, the forecast_role refreshes the forecast on a weekly base and writes into a  `self.context.data_dict["price_forecast"]
So that the units_operator always has an up to date price forecast, but does not have to care about communication or update frequency

**Comment by nick-harder** [comment]
initial implementation of the forecast agent looks great, thanks! We will expand on this foundation in the future work

**Comment by kim-mskw** [comment]
combine forecast role with the putput role and name it data managemnt role. Then it can handle all the data in every variety and give it back to the market participants if needed.

otherwise it is hard to access the historical data for the rl agents, which need this data in their observation space. 

Alternatively, we could play back the historical data via the market cleaning but that seem messy.

**Comment by nick-harder** [comment]
Should we implement this? How do you see it? @kim-mskw @maurerle

**Comment by kim-mskw** [comment]
I think we might have more pressing things on our agenda, right now, because we have to get everything to work for the workshop. Such as functioning learning in some way or documentation and cleaner code.

**Comment by maurerle** [comment]
I think that the current way to receive and set input data or forecasts as it was implemented in #131 is sufficient for now?
If there is need for a separate forecast role or joint role with the output agent, we can revise this..?

**Comment by nick-harder** [comment]
I believe this issue is now resolved with the latest commits from @maurerle
