### ISSUE TITLE
Make multiprocessing mango available on windows

### ISSUE THREAD

**Issue by kim-mskw** [assume-framework/assume#62]
Currently the distribution of the output role process leads to errors when using windows and, hence, has to be hard coded to same_process=True (world.py) if windows is used

**Comment by nick-harder** [comment]
@maurerle is there a solution for this issue or should we for now implement a check if this function is supported and set True if not instead of the hard coded solution?

**Comment by maurerle** [comment]
I did not have hands on a windows system with conda installed since then, but would like to keep this issue open until I find time to properly fix it

**Comment by maurerle** [comment]
This is fixed by using dill instead of pickle in mango:
To install the latest mango version run:
`pip install -e .`

please give feedback if this resolved the error

**Comment by nick-harder** [comment]
the project file still has the reference to your mango. Should this be changed now to activate this function?

**Comment by maurerle** [comment]
This can't be resolved easily as the scope is still copied using pickle, which somehow behaves weird when not run on linux :shrug: - so the output role only uses a separate process when run on linux, see #199

**Comment by nick-harder** [comment]
This issue is closed for now as it is stalled and is only available on Linux.
