### ISSUE TITLE
Sequential clearing of parallel markets if timing matches

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#76]
Now with CRM and EOM active I am facing a problem, where the EOM and CRM bids are formulated wrong during the hour, when both markets are open. We need to think of a solution to solve this

**Comment by maurerle** [comment]
The issue here is, that both markets did not close yet. So in the hour when both markets are open, the eom can bid 1 MW and additionally bid 800MW on pos_crm (which is wrong)

![image](https://github.com/assume-framework/assume/assets/25026204/40b063bc-b291-4866-9d22-ea0093555f52)


```mermaid
gantt
    title Market Schedule
    dateFormat  YYY-MM-DD HH:mm
    axisFormat %Y-%m-%d %H:%M
    section EOM
    Bidding01 EOM          :a1, 2019-01-01 01:00, 1h
    Delivery01 EOM         :after a1, 1h
    Bidding02 EOM          :a2, 2019-01-01 02:00, 1h
    Delivery02 EOM         :after a2, 1h
    Bidding03 EOM          :a3, 2019-01-01 03:00, 1h
    Delivery03 EOM         :after a3, 1h
    Bidding04 EOM          :a4, 2019-01-01 04:00, 1h
    Delivery04 EOM         :after a4, 1h
    section CRM
    Bidding CRM            :crm01, 2019-01-01 00:00, 30m
    Delivery CRM           :crm02, 2019-01-01 01:00, 4h
    Bidding CRM            :crm03, 2019-01-01 04:00, 30m
    Delivery CRM           :crm04, 2019-01-01 05:00, 4h
```

One solution includes to set `first_delivery: 0h` in the EOM - moving the EOM Bidding for this hour one hour before, so that the bidding period starts do not overlap.
Then, the CRM market first gets 1000MW `capacity_pos` and the EOM market gets 200MW (minimum power).

```mermaid
gantt
    title Market Schedule
    dateFormat  YYY-MM-DD HH:mm
    axisFormat %Y-%m-%d %H:%M
    section EOM
    Bidding01 EOM          :a1, 2019-01-01 01:00, 1h
    Delivery01 EOM         :2019-01-01 01:00, 1h
    Bidding02 EOM          :a2, 2019-01-01 02:00, 1h
    Delivery02 EOM         :2019-01-01 02:00, 1h
    Bidding03 EOM          :a3, 2019-01-01 03:00, 1h
    Delivery03 EOM         :2019-01-01 03:00, 1h
    Bidding04 EOM          :a4, 2019-01-01 04:00, 1h
    Delivery04 EOM         :2019-01-01 04:00, 1h
    section CRM
    Bidding CRM            :crm01, 2019-01-01 00:00, 30m
    Delivery CRM           :crm02, 2019-01-01 01:00, 4h
    Bidding CRM            :crm03, 2019-01-01 04:00, 30m
    Delivery CRM           :crm04, 2019-01-01 05:00, 4h
```

Another solution would be to set `first_delivery: 5h` resulting in bidding 1000 MW on the EOM market for all hours starting after 05:00 and bidding 800MW of `capacity_neg` - as CRM is then bidding "behind the EOM":

```mermaid
gantt
    title Market Schedule
    dateFormat  YYY-MM-DD HH:mm
    axisFormat %Y-%m-%d %H:%M
    section EOM
    Bidding01 EOM          :a1, 2019-01-01 01:00, 1h
    Delivery01 EOM         :2019-01-01 05:00, 1h
    Bidding02 EOM          :a2, 2019-01-01 02:00, 1h
    Delivery02 EOM         :2019-01-01 06:00, 1h
    Bidding03 EOM          :a3, 2019-01-01 03:00, 1h
    Delivery03 EOM         :2019-01-01 07:00, 1h
    Bidding04 EOM          :a4, 2019-01-01 04:00, 1h
    Delivery04 EOM         :2019-01-01 08:00, 1h
    section CRM
    Bidding CRM            :crm01, 2019-01-01 00:00, 30m
    Delivery CRM           :crm02, 2019-01-01 01:00, 4h
    Bidding CRM            :crm03, 2019-01-01 04:00, 30m
    Delivery CRM           :crm04, 2019-01-01 05:00, 4h
```

**Comment by maurerle** [comment]
But the "correct" way to solve this would be to introduce a "vorgemerkt" series in ther bidding_agent with the amount which did not get accepted yet, but was sent to the market and can therefore not be bid on other markets..

I think that producing such mermaid gantt charts of the event order could be something helpful for the framework too and should be doable.

But from what I saw, the market events are working "as expected"

**Comment by nick-harder** [comment]
issue will be adressed during the validation study
