### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#83]
We need a robust testing framework within the project if we want to continue its expansion in a sustanable way. For this we need to implement multiple series touching base aspects of the framework. Especially for: units, bidding strategies, market clearing algorithms.
We should think about the general concept and workload distribution.

**Comment by maurerle** [comment]
I think that this general issue is completed, as we now have a test coverage of nearly 70%.
But we should consider adding tests for new features as we go.
