### ISSUE TITLE
Check if simulation_id is already in db and warn user that data will be overwritten

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#84]
```
            #TODO: check if simulation_id is already in db
```

https://github.com/assume-framework/assume/blob/368473cf8ba9ba8e17774b7e9f5d0496914ef07e/assume/common/outputs.py#L61-L63

**Comment by maurerle** [comment]
The comment said:
> and warn user if so give the option to abort or continue and delete old data

I don't like to add user interaction there. Maybe we can think about adding this to the cli.py - as this is always run by a user

**Comment by nick-harder** [comment]
As this hasn't been an issue until now, this issue is closed for now. Such a check will be a part of future development of the scenario loader script with possible GUI implementation.
