### ISSUE TITLE
Document latest additions of units and mechanisms

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#90]
We need to expand our readthedocs website as we go and implement new types of units, markets, algorithms, and so on. Now we need to add documentation for:
**Units:**

- [x] - power plants
- [x] - storage units
- [x] - demand

**Common:**

- [x] Outputs role
- [ ] Config files
- [ ] reinforcment learning 

**Strategies**
- [x] reinforcement learning startegies
- [x] conventional strategies

**Markets:**

- [x] - Market config

**General**
- [ ] scenarios
- [ ] establish general scenario description layout?

**Comment by nick-harder** [comment]
@maurerle do you a suggestion of the best way to document the config file parameters? Do you maybe know any good examples where it has been done?

**Comment by nick-harder** [comment]
@kim-mskw please refer your HiWis who is doing the docs to this issue, so they can document the progress over here and also create related branches

**Comment by maurerle** [comment]
I would expect to have a `config.yml.example` somewhere which has comments to clarify everything.
Additionally, a documentation of the scenarios on readthedocs.

But currently, the config file is not self-contained and relies on the input folder too..

**Comment by maurerle** [comment]
superseded by #146
