### ISSUE TITLE
Outputs function error

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#91]
Since units_meta no longer exists, this returns an error. I will just remove this line since the capacity factor is not really a necessary parameter in my opinion.

https://github.com/assume-framework/assume/blob/cb39d38ea11bc97a568508756da1b218849a7a7d/assume/common/outputs.py#L234

**Comment by maurerle** [comment]
Well it is a relevant KPI in other terms, so I would not just remove it - changing units_meta to power_plant_meta would be the better fix

**Comment by nick-harder** [comment]
yeah, true. changed
