### ISSUE TITLE
Merge units definition and their bidding strategies definition into one file

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#95]
I believe it is a bad idea to have a seperate file for bidding strategies as it is hard to prepare scenarios and not to forget to include the same demand, power plant and storage units in the bidding strategies file. I propose to merge the definition of bidding strategies into the units file as extra parameter. How do you find this proposal @kim-mskw @maurerle @Manish-Khanra?

**Comment by kim-mskw** [comment]
I like this idea. I just wondered about something similar when coding the learning.

**Comment by maurerle** [comment]
I think thats good too.
We should do this after merging the refactoring in #96

**Comment by nick-harder** [comment]
Issue is now fixed and merged into main
